version: '3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: '1212'
      POSTGRES_DB: dump
    networks:
      - test
  make-interface-dump:
    build:
      context: ./
      dockerfile: ./make_interface_dump/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "50051:50051"
    env_file: 
      - .env
    networks:
      - test
  get-interface-dumps:
    build:
      context: ./
      dockerfile: ./get_interface_dumps/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "50052:50052"
    env_file: 
      - .env
    networks:
      - test
  client-make:
    build:
      context: ./
      dockerfile: ./client_make/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file: 
      - .env
    networks:
      - test
  client-get:
    build:
      context: ./
      dockerfile: ./client_get/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8082"
    env_file: 
      - .env
    networks:
      - test

volumes:
  postgres_data:

networks:
  test:
    external: true
