// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: get_interface_dumps.proto

package grpc_from0

import (
	context "context"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInterfaceDumpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastCount int32 `protobuf:"varint,1,opt,name=last_count,json=lastCount,proto3" json:"last_count,omitempty"`
}

func (x *GetInterfaceDumpsRequest) Reset() {
	*x = GetInterfaceDumpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_interface_dumps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInterfaceDumpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceDumpsRequest) ProtoMessage() {}

func (x *GetInterfaceDumpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_interface_dumps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceDumpsRequest.ProtoReflect.Descriptor instead.
func (*GetInterfaceDumpsRequest) Descriptor() ([]byte, []int) {
	return file_get_interface_dumps_proto_rawDescGZIP(), []int{0}
}

func (x *GetInterfaceDumpsRequest) GetLastCount() int32 {
	if x != nil {
		return x.LastCount
	}
	return 0
}

type Dumps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dumps []*Dump `protobuf:"bytes,1,rep,name=dumps,proto3" json:"dumps,omitempty"`
}

func (x *Dumps) Reset() {
	*x = Dumps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_interface_dumps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dumps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dumps) ProtoMessage() {}

func (x *Dumps) ProtoReflect() protoreflect.Message {
	mi := &file_get_interface_dumps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dumps.ProtoReflect.Descriptor instead.
func (*Dumps) Descriptor() ([]byte, []int) {
	return file_get_interface_dumps_proto_rawDescGZIP(), []int{1}
}

func (x *Dumps) GetDumps() []*Dump {
	if x != nil {
		return x.Dumps
	}
	return nil
}

type Dump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mac     string `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip      string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Dns     string `protobuf:"bytes,5,opt,name=dns,proto3" json:"dns,omitempty"`
	Gateway string `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
}

func (x *Dump) Reset() {
	*x = Dump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_interface_dumps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dump) ProtoMessage() {}

func (x *Dump) ProtoReflect() protoreflect.Message {
	mi := &file_get_interface_dumps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dump.ProtoReflect.Descriptor instead.
func (*Dump) Descriptor() ([]byte, []int) {
	return file_get_interface_dumps_proto_rawDescGZIP(), []int{2}
}

func (x *Dump) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dump) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dump) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Dump) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Dump) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *Dump) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

var File_get_interface_dumps_proto protoreflect.FileDescriptor

var file_get_interface_dumps_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f,
	0x64, 0x75, 0x6d, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x2e, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x70, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x64, 0x75, 0x6d, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x70, 0x73, 0x22,
	0x78, 0x0a, 0x04, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x61, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6e, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x32, 0x7e, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x73, 0x12, 0x69,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x75,
	0x6d, 0x70, 0x73, 0x12, 0x23, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x44, 0x75, 0x6d, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x72, 0x63, 0x65, 0x2e, 0x44, 0x75, 0x6d, 0x70, 0x73, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x17, 0x12, 0x15, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x7d, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x6b, 0x72, 0x75, 0x73, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x66, 0x72, 0x6f, 0x6d, 0x30, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_interface_dumps_proto_rawDescOnce sync.Once
	file_get_interface_dumps_proto_rawDescData = file_get_interface_dumps_proto_rawDesc
)

func file_get_interface_dumps_proto_rawDescGZIP() []byte {
	file_get_interface_dumps_proto_rawDescOnce.Do(func() {
		file_get_interface_dumps_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_interface_dumps_proto_rawDescData)
	})
	return file_get_interface_dumps_proto_rawDescData
}

var file_get_interface_dumps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_get_interface_dumps_proto_goTypes = []interface{}{
	(*GetInterfaceDumpsRequest)(nil), // 0: ecommerce.GetInterfaceDumpsRequest
	(*Dumps)(nil),                    // 1: ecommerce.Dumps
	(*Dump)(nil),                     // 2: ecommerce.Dump
}
var file_get_interface_dumps_proto_depIdxs = []int32{
	2, // 0: ecommerce.Dumps.dumps:type_name -> ecommerce.Dump
	0, // 1: ecommerce.GetInterfaceDumps.GetInterfaceDumps:input_type -> ecommerce.GetInterfaceDumpsRequest
	1, // 2: ecommerce.GetInterfaceDumps.GetInterfaceDumps:output_type -> ecommerce.Dumps
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_get_interface_dumps_proto_init() }
func file_get_interface_dumps_proto_init() {
	if File_get_interface_dumps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_interface_dumps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInterfaceDumpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_interface_dumps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dumps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_interface_dumps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_interface_dumps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_interface_dumps_proto_goTypes,
		DependencyIndexes: file_get_interface_dumps_proto_depIdxs,
		MessageInfos:      file_get_interface_dumps_proto_msgTypes,
	}.Build()
	File_get_interface_dumps_proto = out.File
	file_get_interface_dumps_proto_rawDesc = nil
	file_get_interface_dumps_proto_goTypes = nil
	file_get_interface_dumps_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetInterfaceDumpsClient is the client API for GetInterfaceDumps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetInterfaceDumpsClient interface {
	GetInterfaceDumps(ctx context.Context, in *GetInterfaceDumpsRequest, opts ...grpc.CallOption) (*Dumps, error)
}

type getInterfaceDumpsClient struct {
	cc grpc.ClientConnInterface
}

func NewGetInterfaceDumpsClient(cc grpc.ClientConnInterface) GetInterfaceDumpsClient {
	return &getInterfaceDumpsClient{cc}
}

func (c *getInterfaceDumpsClient) GetInterfaceDumps(ctx context.Context, in *GetInterfaceDumpsRequest, opts ...grpc.CallOption) (*Dumps, error) {
	out := new(Dumps)
	err := c.cc.Invoke(ctx, "/ecommerce.GetInterfaceDumps/GetInterfaceDumps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetInterfaceDumpsServer is the server API for GetInterfaceDumps service.
type GetInterfaceDumpsServer interface {
	GetInterfaceDumps(context.Context, *GetInterfaceDumpsRequest) (*Dumps, error)
}

// UnimplementedGetInterfaceDumpsServer can be embedded to have forward compatible implementations.
type UnimplementedGetInterfaceDumpsServer struct {
}

func (*UnimplementedGetInterfaceDumpsServer) GetInterfaceDumps(context.Context, *GetInterfaceDumpsRequest) (*Dumps, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterfaceDumps not implemented")
}

func RegisterGetInterfaceDumpsServer(s *grpc.Server, srv GetInterfaceDumpsServer) {
	s.RegisterService(&_GetInterfaceDumps_serviceDesc, srv)
}

func _GetInterfaceDumps_GetInterfaceDumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceDumpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetInterfaceDumpsServer).GetInterfaceDumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.GetInterfaceDumps/GetInterfaceDumps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetInterfaceDumpsServer).GetInterfaceDumps(ctx, req.(*GetInterfaceDumpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetInterfaceDumps_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.GetInterfaceDumps",
	HandlerType: (*GetInterfaceDumpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterfaceDumps",
			Handler:    _GetInterfaceDumps_GetInterfaceDumps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_interface_dumps.proto",
}
