// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: get_interface_dumps.proto

/*
Package grpc_from0 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package grpc_from0

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

func request_GetInterfaceDumps_GetInterfaceDumps_0(ctx context.Context, marshaler runtime.Marshaler, client GetInterfaceDumpsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetInterfaceDumpsRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["last_count"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "last_count")
	}

	protoReq.LastCount, err = runtime.Int32(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "last_count", err)
	}

	msg, err := client.GetInterfaceDumps(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GetInterfaceDumps_GetInterfaceDumps_0(ctx context.Context, marshaler runtime.Marshaler, server GetInterfaceDumpsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetInterfaceDumpsRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["last_count"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "last_count")
	}

	protoReq.LastCount, err = runtime.Int32(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "last_count", err)
	}

	msg, err := server.GetInterfaceDumps(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterGetInterfaceDumpsHandlerServer registers the http handlers for service GetInterfaceDumps to "mux".
// UnaryRPC     :call GetInterfaceDumpsServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterGetInterfaceDumpsHandlerFromEndpoint instead.
func RegisterGetInterfaceDumpsHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GetInterfaceDumpsServer) error {

	mux.Handle("GET", pattern_GetInterfaceDumps_GetInterfaceDumps_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GetInterfaceDumps_GetInterfaceDumps_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GetInterfaceDumps_GetInterfaceDumps_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterGetInterfaceDumpsHandlerFromEndpoint is same as RegisterGetInterfaceDumpsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGetInterfaceDumpsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGetInterfaceDumpsHandler(ctx, mux, conn)
}

// RegisterGetInterfaceDumpsHandler registers the http handlers for service GetInterfaceDumps to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGetInterfaceDumpsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGetInterfaceDumpsHandlerClient(ctx, mux, NewGetInterfaceDumpsClient(conn))
}

// RegisterGetInterfaceDumpsHandlerClient registers the http handlers for service GetInterfaceDumps
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GetInterfaceDumpsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GetInterfaceDumpsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GetInterfaceDumpsClient" to call the correct interceptors.
func RegisterGetInterfaceDumpsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client GetInterfaceDumpsClient) error {

	mux.Handle("GET", pattern_GetInterfaceDumps_GetInterfaceDumps_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GetInterfaceDumps_GetInterfaceDumps_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GetInterfaceDumps_GetInterfaceDumps_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_GetInterfaceDumps_GetInterfaceDumps_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"dump", "v1", "last_count"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_GetInterfaceDumps_GetInterfaceDumps_0 = runtime.ForwardResponseMessage
)
